[General]
__userfile__=true
size=@Size(600 400)

[SavedConfigs]
SavedSettings\1\date=2025-11-09T17:25:10
SavedSettings\1\name=Sun Nov 9 17:25:10 2025
SavedSettings\1\settings\1\connected=true
SavedSettings\1\settings\1\currentMode=93
SavedSettings\1\settings\1\currentModeHeight=1800
SavedSettings\1\settings\1\currentModeRate=120.00029754638672
SavedSettings\1\settings\1\currentModeWidth=2880
SavedSettings\1\settings\1\enabled=true
SavedSettings\1\settings\1\hash=227c02047c5065fba70da761b7a267c5
SavedSettings\1\settings\1\name=eDP
SavedSettings\1\settings\1\primary=true
SavedSettings\1\settings\1\rotation=1
SavedSettings\1\settings\1\xPos=0
SavedSettings\1\settings\1\yPos=0
SavedSettings\1\settings\2\connected=false
SavedSettings\1\settings\2\hash=
SavedSettings\1\settings\2\name=DisplayPort-0
SavedSettings\1\settings\3\connected=false
SavedSettings\1\settings\3\hash=
SavedSettings\1\settings\3\name=DisplayPort-1
SavedSettings\1\settings\4\connected=false
SavedSettings\1\settings\4\hash=
SavedSettings\1\settings\4\name=DisplayPort-2
SavedSettings\1\settings\5\connected=false
SavedSettings\1\settings\5\hash=
SavedSettings\1\settings\5\name=DisplayPort-3
SavedSettings\1\settings\6\connected=false
SavedSettings\1\settings\6\hash=
SavedSettings\1\settings\6\name=DisplayPort-4
SavedSettings\1\settings\7\connected=false
SavedSettings\1\settings\7\hash=
SavedSettings\1\settings\7\name=DisplayPort-5
SavedSettings\1\settings\8\connected=false
SavedSettings\1\settings\8\hash=
SavedSettings\1\settings\8\name=DisplayPort-6
SavedSettings\1\settings\9\connected=false
SavedSettings\1\settings\9\hash=
SavedSettings\1\settings\9\name=DisplayPort-7
SavedSettings\1\settings\size=9
SavedSettings\size=1

[currentConfig]
settings\1\connected=true
settings\1\currentMode=93
settings\1\currentModeHeight=1800
settings\1\currentModeRate=120.00029754638672
settings\1\currentModeWidth=2880
settings\1\enabled=true
settings\1\hash=227c02047c5065fba70da761b7a267c5
settings\1\name=eDP
settings\1\primary=true
settings\1\rotation=1
settings\1\xPos=0
settings\1\yPos=0
settings\2\connected=false
settings\2\hash=
settings\2\name=DisplayPort-0
settings\3\connected=false
settings\3\hash=
settings\3\name=DisplayPort-1
settings\4\connected=false
settings\4\hash=
settings\4\name=DisplayPort-2
settings\5\connected=false
settings\5\hash=
settings\5\name=DisplayPort-3
settings\6\connected=false
settings\6\hash=
settings\6\name=DisplayPort-4
settings\7\connected=false
settings\7\hash=
settings\7\name=DisplayPort-5
settings\8\connected=false
settings\8\hash=
settings\8\name=DisplayPort-6
settings\9\connected=false
settings\9\hash=
settings\9\name=DisplayPort-7
settings\size=9
