################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor=,preferred,auto,auto

env = GDK_SCALE=1
env = GDK_DPI_SCALE=1
env = XDG_CURRENT_DESKTOP=Hyprland
env = GDK_DPI=96
env = QT_SCALE_FACTOR=1
env = SDL_VIDEO_X11_DPI=96
monitor= eDP-1, 2880x1800@120, 0x0, 2.25,
monitor= eDP-2, 2880x1800@120, 0x0, 2, 
monitor= DP-2, 1920x1080@60, 0x-1080, 1, 
monitor= HDMI-A-1, 1920x1080@60, 0x-1080, 1

