cursor #e6f0ff
cursor_text_color #ffffff

foreground            #e6f0ff
background            #000000
selection_foreground  #000000
selection_background  #999999
url_color             #fc03eb

color0   #000000
color1   #ff001c
color2   #50fc02
color3   #ffc400
color4   #ef00df
color5   #74006c
color6   #fc03eb
color7   #ffe0fc
color8   #a38ba2
color9   #ff4257
color10  #85ff4e
color11  #ffd64e
color12  #ff28f0
color13  #ff4ef2
color14  #ff8df7
color15  #fff2fe
