cursor #c0caf5
cursor_text_color #545c7e

foreground            #c0caf5
background            #000000
selection_foreground  #000000
selection_background  #bb9af7
url_color             #d07e9a

color0   #000000
color1   #ef6b71
color2   #82d068
color3   #ffe172
color4   #c56888
color5   #000000
color6   #D07E9A
color7   #dacdcd
color8   #3b3333
color9   #ff9fa3
color10  #b8f9a2
color11  #ffeca5
color12  #e498b2
color13  #ffb8d0
color14  #ffd1e1
color15  #fff8f8
