cursor #e6f0ff
cursor_text_color #ffffff

foreground            #e6f0ff
background            #000000
selection_foreground  #000000
selection_background  #999999
url_color             #ca0344

color0   #000000
color1   #e80009
color2   #34ca02
color3   #fcc800
color4   #bf003e
color5   #5d001e
color6   #ca0344
color7   #d4bbc3
color8   #836f76
color9   #ff4249
color10  #75f24b
color11  #ffda4f
color12  #de2460
color13  #ff4f88
color14  #ff8db2
color15  #fff2f6
