# vim:ft=kitty

## name: why
## license: MIT
## author: even bother trying
background                #000000
foreground                #ffffff

selection_background      #1c1c1c
selection_foreground      #c0bfbc

url_color                 #1a5fb4

wayland_titlebar_color    system
macos_titlebar_color      system

cursor                    #FFFFFF
cursor_text_color         #000000

active_border_color       #1e1e1e
inactive_border_color     #282828
bell_border_color         #ed333b
visual_bell_color         none

active_tab_background     #101010
active_tab_foreground     #fcfcfc
inactive_tab_background   #1c1c1c
inactive_tab_foreground   #b0afac
tab_bar_background        none
tab_bar_margin_color      none

# black
color0                    #000000 
color8                    #999999 

#red
color1                    #CC0000
color9                    #FF0000

# green
color2                    #00FF00
color10                   #77FF77

# orange
color3                    #FF7700

# yellow
color11                   #FFFF00

# blue
color4                    #0084D1
color12                   #55DDFF

# purple/pink  
color5                    #770088
color13                   #FF00CC

# cyan
color6                    #0088AA
color14                   #00FFFF  

# white
color7                    #CCCCCC
color15                   #FFFFFF
