Net/ThemeName "Flat-Remix-GTK-Green-Darkest-Solid"
Net/IconThemeName "Papirus"
Gtk/CursorThemeName "default"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 0
Xft/HintStyle "hintnone"
Xft/RGBA "rgb"
