-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(7dcfff)",
			inactive_border = "rgb(565f89)",
		},
	},
	group = {
		col = {
			border_active = "rgb(7dcfff)",
			border_inactive = "rgb(565f89)",
			border_locked_active = "rgb(f7768e)",
			border_locked_inactive = "rgb(565f89)",
		},
		groupbar = {
			col = {
				active = "rgb(7dcfff)",
				inactive = "rgb(565f89)",
				locked_active = "rgb(f7768e)",
				locked_inactive = "rgb(565f89)",
			},
		},
	},
})
