monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_65_00.6.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
        api.alsa.disable-mixer = true
      }
    }
  }
]
