monitor.alsa.rules = {
  {
    matches = {
      { { "node.name", "matches", "alsa_output.*" }, },
    },
    apply_properties = {
      ["api.alsa.use-mixer-name"] = "PCM",
      ["api.alsa.soft-mixer"] = true,
      ["api.alsa.disable-mixer"] = true,
    },
  },
}
